# Yoink ideas from Godot's issue template
# https://github.com/godotengine/godot/blob/master/.github/ISSUE_TEMPLATE/config.yml

blank_issues_enabled: false

contact_links:
  - name: Lore proposals
    url: https://github.com/Perkedel/AfterChurch/issues
    about: Please submit feature proposals on the After Church repository, not here.

  - name: JOELwindows7 Contact Collections
    url: https://cointr.ee/joelwindows7
    about: Joel's account collection. 