# Yoink template from Godot's issue template
# https://github.com/godotengine/godot/blob/master/.github/ISSUE_TEMPLATE/bug_report.yml
# https://github.com/godotengine/godot-proposals/blob/master/.github/ISSUE_TEMPLATE/feature_enhancement_proposal.yml
# https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository

name: Lore Proposal
description: Open a new lore proposal
labels: ["proposal"]
assignees:
  - JOELwindows7
body:

- type: markdown
  attributes:
    value: |
      # Lore Proposal
      - Write a descriptive proposal title above.
      - Search [open](https://github.com/Perkedel/After-Church/issues) and [closed](https://github.com/Perkedel/After-Church/issues?q=is%3Aissue+is%3Aclosed) proposals to ensure the lore has not already been suggested.
      - This is not for asking reupload & piracy. Please wait for the template from Admiral Zumi of Xop1r4t3 Eenvreensment to be added later.

- type: input
  id: title
  attributes:
    label: Write the merchandise / lore name
    description: What's the name of the Storyful Video game, Film, Manga / Comic, Novel / Visual Novel, etc.?
    placeholder: Example - "Little Nightmares"
  validations:
    required: true

- type: input
  id: lore-owner
  attributes:
    label: Production from
    description: What's the name of the production company? who's the current lore owner? &/or author of the lore itself?
    placeholder: Example - "Tarsier Studios (Published by Bandai Namco)"
  validations:
    required: true
  
- type: textarea
  id: details
  attributes:
    label: Lore Details
    description: Describe the lore in detail. At least by synopsis of what happened, what was the main character, how's the end & what current situation is there right now, etc.
    placeholder: Example - "Once upon a time, there is a kid in yellow jacket awaken..."
  validations:
    required: true

- type: textarea
  id: link
  attributes:
    label: Access from
    description: Please provide links where can we access the lore.
    placeholder: | 
      Example:  
      # Sauces
      - https://store.steampowered.com/app/424840/Little_Nightmares/
      - https://store.steampowered.com/app/860510/Little_Nightmares_II/

    value: |
      # Sauces
      -
      -
      -
    render: markdown
  validations:
    required: true

- type: markdown
  attributes:
    value: |
      # Costs & Risks
      to consider before making fanart of this lore.

- type: dropdown
  id: license-to-access
  attributes:
    label: License to access
    description: How do we access this lore? This is very important to consider for us to ensure we correctly build spending strategies & avoid recklessly putting our souls in debts. Not to be confused with Business acquirements!
    options:
      - GRATIS 100% (even the DLCs are **all $0**)
      - Paid Lifetime (or Free to access with optional **paid** DLCs)
      - Sell Soul (Subscription)
  validations:
    required: true

- type: checkboxes
  id: holder-special-behaviours
  attributes:
    label: Lore holders & lore itself "special" behaviours
    description: Please evaluate & mark accordingly the "special" behaviour of the current lore owner, production company, &/or the lore author as well as the lore itself.
    options:
      - label: Kamatussa (Hates NFSW, rule34 and such)
      - label: Litigation mania (likes to sue fans for making fanarts, fan games, etc.) (e.g. Nintendo)
      - label: Mysoginist (hates female) / Kill all men (hates male)
      - label: Reckless groom irl (pedophile) (**NOT TO BE CONFUSED WITH LOLICON** (likes child in fictional, even sexually))
      - label: Doxxer (collects your private key datas, has exchange activities to them) (.e.g. Google, Meta / Facebook, Microsoft)
      - label: karen (wants to win argument at all time & wrath if lose) (bashes other lores)
      - label: racist (hates white, black, asian, latino, etc.)
      - label: Money-eyed (partialist, charges everything possible for money or anything exchanges, expect user to pay extra to win. Next level of Paywallist)
      - label: Elusive (often disappear &/or along with the lore &/or files)
      - label: Digital Restriction Management (either the lore or the software / film / book of it has DRM to restrict access to certain countries, paranoia, etc.) (Marking this will notify Admiral Zumi & other pirates to pirate the lore & may involves Lorecaster if necessary)
      - label: Homosexual (Lesbian, Gay) / special sexuals (Pansexual, asexual, etc.)
      - label: Super Procrastinate (takes way extremely long to release new part of the lore such as Episodes, Seasons, Sequels, Spinoffs, new lores, etc.)
      - label: Unstable (state of the lore storyline keeps changing everytime) (NOT TO BE CONFUSED WITH Choose your path, Rolling Release)
      - label: Dissenseful (lore doesn't make sense, random actions often happen out of nowhere, no clear purpose of the lore, &/OR terrible signature often dominates the situations) (e.g. High Spice Guardian)
      - label: Radioactive (has parameter and situations deemed radioactive & likely came because of trauma in the past from either parties) (e.g. bbpanzu x madii Vs. Sky (now Sky belongs to KitsuneSkull after stuffs)) (Marking this causes Lorecaster to be involved)
      - label: Empty (has no official lore at all & user can create their own) (e.g. Surreal Memes)
      - label: Unfinished (lore is unfinished indefinitely, either on purpose or due to unforseen circumstances)

